### ISSUE TITLE
Build fail with android com.bugsnag.android.gradle 8+

### ISSUE THREAD

**Issue by meabed** [bugsnag/bugsnag-expo#102]
Expo prebuild:

Build start failing because of the latest android gradle plugin is not versioned.

```
    apply plugin: 'com.bugsnag.android.gradle'

    bugsnag {
        uploadReactNativeMappings = true
    }

```

The latest release here is gradle 8: https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases

The build error.

A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.bugsnag.android.gradle'.
   > Using com.bugsnag.android.gradle:8+ with Android Gradle Plugin < 8 is not supported. Either upgrade the Android Gradle Plugin to 8, or use an earlier version of the BugSnag Gradle Plugin. For more information about this change, see https://docs.bugsnag.com/build-integrations/gradle/

**Comment by hamudi-ahmed** [comment]
Hi @meabed thanks for the report! 

We've now released a fix for this in [v47.1.1](https://github.com/bugsnag/bugsnag-expo/releases/tag/v47.1.1), [v46.0.3](https://github.com/bugsnag/bugsnag-expo/releases/tag/v46.0.3) and [v45.1.3](https://github.com/bugsnag/bugsnag-expo/releases/tag/v47.1.1) of `@bugsnag/plugin-expo-eas-sourcemaps` 🎉

**Comment by lucasklaassen** [comment]
@yousif-bugsnag when will you be publishing 47.1.1 to npm?

**Comment by johnkiely1** [comment]
Hey @lucasklaassen 

Only `@bugsnag/plugin-expo-eas-sourcemaps` required an update, for which [v47.1.1 is already on npm](https://www.npmjs.com/package/@bugsnag/plugin-expo-eas-sourcemaps/v/47.1.1).

`@bugsnag/expo` itself did not change, so there's no corresponding version on npm

So to update you only need to bump the version of `@bugsnag/plugin-expo-eas-sourcemaps` to v47.1.1
