### ISSUE TITLE
Expo: Android: upload to bugsnag requires api key

### ISSUE THREAD

**Issue by meabed** [bugsnag/bugsnag-expo#114]
After the update, We get this error: 

in fastlane step: send_build_to_bugsnag
[12:40:16]: A Bugsnag API key is required to release a build. Set com.bugsnag.android.API_KEY in your AndroidManifest.xml to detect API key automatically.

it was working before the upgrade.

I think if this meta-info is need, it should be add by the plugin in the pre-build step instead of us doing it.

**Comment by tomlongridge** [comment]
Hi @meabed – which version were you updating from/to?

**Comment by meabed** [comment]
@tomlongridge latest version 5 with expo 48

**Comment by tomlongridge** [comment]
@meabed – I'm not sure what you mean by version 5? Was it a change in BugSnag library or Expo that seems to have caused the problem?

Also, if I understand you correctly, you're using Fastlane to publish an Expo app? Is that built with EAS?

**Comment by meabed** [comment]
@tomlongridge I think the new version of the plugin doesn't add the <meta-data api key> in android manifest correctly in Expo

**Comment by johnkiely1** [comment]
Hi @meabed, as you will see we have made the code changes for reinstating the API key in the manifest and is just waiting to be released. 

It is worth mentioning however the EAS plugin will upload source maps as part of the EAS build, so the Fastlane plugin may not be required for your builds unless you want to send additional metadata. 

Out of interest it would be good to understand your build process a bit more if you are willing to share some details? How are you using Fastlane within the process of building your Expo app? Is that built with EAS?

**Comment by johnkiely1** [comment]
The api key has now been reinstated in [v48.1.0.](https://github.com/bugsnag/bugsnag-expo/releases/tag/v48.1.0) Let us know if you have any further issues with it.
