### ISSUE TITLE
47.1.1 was not published to NPM

### ISSUE THREAD

**Issue by corymsmith** [bugsnag/bugsnag-expo#115]
Theres a 47.1.1 release on Github that fixes a gradle issue but it wasn't published to NPM

<img width="823" alt="Screenshot 2023-03-09 at 12 54 09 PM" src="https://user-images.githubusercontent.com/7315/224139134-36848289-8322-4d91-aa70-874a8d4667b7.png">

**Comment by corymsmith** [comment]
Any ideas @yousif-bugsnag? Are you able to publish that?

**Comment by hannah-smartbear** [comment]
Hi @corymsmith, only @bugsnag/plugin-expo-eas-sourcemaps required an update, for which v47.1.1 is already on npm.
@bugsnag/expo itself did not change, so there's no corresponding version on npm
So to update you only need to bump the version of @bugsnag/plugin-expo-eas-sourcemaps to v47.1.1
