### ISSUE TITLE
Plugins order conflict - @bugsnag/plugin-expo-eas-sourcemaps && sentry-expo

### ISSUE THREAD

**Issue by MortadhaFadhlaoui** [bugsnag/bugsnag-expo#130]
### Describe the bug
trying to integrate `sentry` at the same time as we have `bugsnag` works fine. we notice that The `@bugsnag/plugin-expo-eas-sourcemaps` isn't too friendly to other scripts.

Having this order in `app.config.ts`
```
plugins: [
...
'@bugsnag/plugin-expo-eas-sourcemaps',
'sentry-expo',
...
]
```

Will generate this issue 
`PhaseScriptExecution Upload\ source\ maps\ to\ Bugsnag /Users/expo/Library/Developer/Xcode/DerivedData/projectName/Build/Intermediates.noindex/ArchiveIntermediates/projectName/IntermediateBuildFilesPath/projectName.build/Release-iphoneos/projectName.build/Script.sh (in target 'projectName' from project 'projectName')`

changing the order works fine 
```
plugins: [
...
'sentry-expo',
'@bugsnag/plugin-expo-eas-sourcemaps',
...
]
```

### Steps to reproduce
Setup `Sentry` and `Bugsnag` in same project outing the plugins in the order mentioned above.

### Environment
* Bugsnag version: 48.1.0
* Expo SDK version (e.g. SDK 44): 48
* Device (e.g. iphonex): IPhone SE

**Comment by matthewjhowells** [comment]
Hi @MortadhaFadhlaoui , 

Thanks for reaching out. 

Would you be able to share some more information on the error you are seeing. For instance, do you have a full stack trace of the error you can share with us?

As this is a public thread, please feel free to send any additional details to support@bugsnag.com.

**Comment by johnkiely1** [comment]
Hi @MortadhaFadhlaoui, have you seen the message above? It would be good to understand the actual error being thrown or what the behavior is. Thanks

**Comment by johnkiely1** [comment]
Closing this out as we have not had a response in a while and need more information to investigate. 

Generally we would recommend against having multiple error monitoring libraries in the same application as they may conflict with each other. While Bugsnag ensures that any caught errors are rethrown to allow other error monitors to capture it, we are unable to say that for other libraries and have seen issues in the past.

**Comment by summerkiflain** [comment]
@johnkiely1 I am also facing a similar issue, where I am using both, sentry and bugsnag and my EAS build fails with error:
https://github.com/bugsnag/bugsnag-expo/issues/184#issuecomment-2282274843

I have tried changing the order of the expo plugins for both sentry and bugsnag but it doesn't work for me and eas build keeps failing, although it works fine if I only use 1 of the error tracking library, either sentry or bugsnag.

**Comment by clr182** [comment]
Hi @summerkiflain 

Due to the possibility of conflicts between the two error monitoring SDKs our recommendation would be to build with only one of these libraries, either BugSnag or Sentry.
