### ISSUE TITLE
App crashes after eas update, works locally

### ISSUE THREAD

**Issue by maciekstosio** [bugsnag/bugsnag-expo#142]
### Describe the bug
Hi, I'm added bugsnag to my project and I get the data from local testing, but when I "publish" my app through `eas update` it crashes when the code reaches `Bugsnag.start()` (I know it's this line cause I removed it and moved around to test it).
The biggest problem is that I don't know how to get any useful logs when it crashes, I tried to wrap in try catch but it didn't help. If you have an idea how to get the logs, I could try to resolve the issue myself. 

### Steps to reproduce
1. expo init
2. create blank app
3. npx bugsnag-expo-cli init (and follow basic init guide)
4. expo update --platform=ios
5. open expo go and run update
6. see crash

### Environment
* Bugsnag version: latest
* Expo SDK version (e.g. SDK 44): 49.0.5
* Device: iphone 13 mini

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here: https://github.com/maciekstosio/bugsnagerror

**Comment by clr182** [comment]
Hi @maciekstosio,
Thank you for opening this PR. We will review this when priorities allow.

**Comment by hamudi-ahmed** [comment]
A fix for this has now been released in [v49.0.1](https://github.com/bugsnag/bugsnag-expo/releases/tag/v49.0.1)

Thanks again for the contribution @maciekstosio!
