### ISSUE TITLE
Bugsnag generates new Build Phase every `npx expo prebuild`

### ISSUE THREAD

**Issue by pzatorski** [bugsnag/bugsnag-expo#148]
### Describe the bug
Every time the `npx expo prebuild` command is fired it will update the `project.pbxproj` file with new Build Phase of "Upload source maps to Bugsnag".

<img width="487" alt="Screenshot 2023-10-04 at 16 41 44" src="https://github.com/bugsnag/bugsnag-expo/assets/11720377/9c555e84-5e86-44ff-ba9a-b6eb6c7bae16">

### Environment
* Bugsnag version: "@bugsnag/expo": "^49.0.0",
* Expo SDK version: SDK 49
* iOS
* Bare workflow in use of `eas build`

**Comment by clr182** [comment]
Hi @pzatorski 

This seems to be an issue where our configuration plugin is being run each time the`npx expo prebuild` command is called. Thanks to your feedback we now have an item on our backlog aimed at making sure our configuration plugin can be run multiple times. However I have no firm ETA on the release of this. We’ll be sure to keep you informed of any updates.

While we work on a long term solution, we suggest running `npx expo prebuild --clean` which will delete and rebuilt the native directories. This method is recommended by expo for this exact issue. More information can be found here: [Prebuild](https://docs.expo.dev/workflow/prebuild/#clean)

**Comment by clr182** [comment]
Hi @pzatorski 
We have release [v49.0.2 ](https://github.com/bugsnag/bugsnag-expo/releases/tag/v49.0.2) of the expo notifier which should fix the issue you were facing. After updating if you are still experiencing issues please reach out and let us know.

**Comment by i-mighty** [comment]
this issue is back for expo 50.0.6 and @bugsnag/expo 50.0.0

**Comment by toniewypada** [comment]
Hi @i-mighty, could you please share some more details about the issue? Are the commands you’re running, and error message the same as in the initial message? If there are any differences could you please share the examples?

**Comment by i-mighty** [comment]
I am running npx eas build -p ios in github actions. I am not doing anything else. 
The dev build runs well locally.

**Comment by brunowilliang** [comment]
Hey @i-mighty Did you manage to solve this problem? I have the same problem

"@bugsnag/expo": "^50.0.0",
"expo": "^50.0.14",

**Comment by toniewypada** [comment]
Hello @i-mighty and @Brunowilliang 👋🏻,
we were unable to recreate the issue on our end. Could you please provide some additional details, like what is your app configuration, and how is your BugSnag notifier configured including example code snippets? As this is a public thread, please feel free to open a ticket with us directly by contacting [support@bugsnag.com](mailto:support@bugsnag.com)

**Comment by i-mighty** [comment]
@Brunowilliang to solve it, simply set the image: "latest" in your build profile configuration for ios. That fixed it for me.

**Comment by brunowilliang** [comment]
@i-mighty @toniewypada They were already set in my settings, and it keeps giving me an error

**Comment by toniewypada** [comment]
@Brunowilliang thanks for the update. Could you please share the details I've mentioned in my previous comment for further investigation?
