### ISSUE TITLE
Missing Expo 50 Support

### ISSUE THREAD

**Issue by GrahamCampbell** [bugsnag/bugsnag-expo#160]

**Comment by 7ammer** [comment]
Expo 50 has been released https://dev.to/expo/expo-sdk-50-release-do.
Is there anything on the way?

**Comment by clr182** [comment]
Hi :wave: 

Thank you for bringing this to our attention. We do have an item on our backlog aimed at supporting Expo 50. I don't have an ETA on this release, but will be sure to update this thread once we have more information to share.

**Comment by jeokeefe** [comment]
+1 on this... looking to add bugSnag to project. Sentry currently has support for Expo 50... The bugsnag libraries wont even install on 50 due to dependency error. Not really a "Feature Request" as it is tagged, just keeping your product up to date and usable.

**Comment by 7ammer** [comment]
Can anyone here tell me what past release schedules have been like with expo updates? I'm pretty new to `bugsnag-expo` so am trying to gauge expectations. I've had to switch to Crashlytics for now, which is not a nice experience.

**Comment by jeokeefe** [comment]
I switched to Sentry.io. It was really straightforward. They have Expo 50
support.



--

Capt. John O'Keefe
FOUNDER, YACHTWAVE
USCG 100 GT MASTER

www.yachtwave.com  |  ***@***.*** ***@***.***>

935 N Beneva Rd, Ste 609, Sarasota, FL 34232
<https://maps.google.com/?q=935+N+Beneva+Rd,+Ste+609+PMB+2056,+Sarasota,+FL+34232>

**Comment by clr182** [comment]
Hi :wave: 

We are actively working on support for Expo 50 and hope to have a release out in the near future. Once support has been released we will update this thread.

**Comment by ivan-jorge001** [comment]
is there an ETA on this, is near future a couple of days/months 
Reason i asked is because my project is in expo v50 and i was hoping to use bugsnag which right now i cant

**Comment by tomlongridge** [comment]
@ivan-jorge001 - we hope to get a release out this week. We are actively working on it but the upgrade has so far proven non-trivial from our perspective, but this is largely due to the impact on our build and CI rather than the library itself.

**Comment by clr182** [comment]
Hi all :wave: 

Thank you for your patience.

We have just release a [new version](https://github.com/bugsnag/bugsnag-expo/releases/tag/v50.0.0) of the expo notifier which adds expo 50 support.

After updating your notifier to the latest release you seen any issues, then please let us know and we can investigate further.
