### ISSUE TITLE
Add Support for Expo SDK 51

### ISSUE THREAD

**Issue by diegocuehdz** [bugsnag/bugsnag-expo#178]
### Description

Expo SDK  51 has been released as of May 7th 2024, hope to have this new version in order to be able to update to the new react native architecture in my projects. 

[ExpoSDK-51 Changelog](https://expo.dev/changelog/2024/05-07-sdk-51)

- Would be nice to now the time estimate to have this update in case that I need to remove bugsnag dependency for the time being in order to update the SDK to the latest. 

- 

**Additional context**

**Comment by mclack** [comment]
Hi @diegocuehdz 

Thank you for raising this with us.

We've created a task to add BugSnag support for Expo 51. We don't currently have an ETA we can share on when this will be available, but we will make sure to post any updates on this thread.

**Comment by toniewypada** [comment]
Hi @diegocuehdz 👋🏻
we've released new version of our Expo notifier, [v51.0.0](https://github.com/bugsnag/bugsnag-expo/releases/tag/v51.0.0), which adds support for Expo v51. 
If you have any questions, please let us know!
