### ISSUE TITLE
Add Support for Expo SDK 52

### ISSUE THREAD

**Issue by diegocuehdz** [bugsnag/bugsnag-expo#201]
Description
Expo SDK 52 has been released as of November 12th 2024, hope to have this new version in order to be able to update to the new react native architecture in my projects.

[ExpoSDK-52 Changelog](https://expo.dev/changelog/2024/11-12-sdk-52)

Would be nice to now the time estimate to have this update in case that I need to remove bugsnag dependency for the time being in order to update the SDK to the latest.

As always thank you very much for your support.

**Comment by toniewypada** [comment]
Hi @diegocuehdz 👋🏻, we have an item on our backlog to add support for Expo SDK 52. We don't have an exact timescale for that at the moment, but we'll make sure that we keep this thread updated on progress.

**Comment by mclack** [comment]
Hi @diegocuehdz 

Thanks for your patience here.

Support for Expo 52 has now been added as part of the `bugsnag-expo` v52.0.0 release: https://github.com/bugsnag/bugsnag-expo/releases/tag/v52.0.0

Please feel free to reach out again if you have any issues after upgrading the BugSnag SDK.

**Comment by diegocuehdz** [comment]
Thank you! Just updated great work as always!
