### ISSUE TITLE
Support SDK 45

### ISSUE THREAD

**Issue by kennethlynne** [bugsnag/bugsnag-expo#35]
### Description

[SDK 45 ](https://blog.expo.dev/expo-sdk-45-f4e332954a68) is released and it is currently not supported

**Describe the solution you'd like**

SDK 45 should be supported

**Describe alternatives you've considered**

**Additional context**

**Comment by gingerbenw** [comment]
Hi @kennethlynne, we have completed [the work required](https://github.com/bugsnag/bugsnag-expo/pull/33) to support v45, and are just awaiting a release from [turtle cli](https://github.com/expo/turtle/issues/399) in order to complete our testing, so you can expect to see this shortly.

Thanks!

**Comment by kennethlynne** [comment]
Looks like it is merged now so this can be closed I guess 🤞

**Comment by gingerbenw** [comment]
Hi @kennethlynne! My apologies for the slow update on this one, we have now released [version 45 of bugsnag-expo](https://github.com/bugsnag/bugsnag-expo/releases/tag/v45.0.0) which supports expo 45.

Many thanks!
