### ISSUE TITLE
expo SDK 46 support

### ISSUE THREAD

**Issue by enagorny** [bugsnag/bugsnag-expo#51]
How fast bugsnag usually adds new expo SDK versions?

**Comment by luke-belton** [comment]
Hi @enagorny - thanks for raising this. We're working on support for Expo 46 and will update you on this thread when it's available 👍

**Comment by kennethlynne** [comment]
Any rough E.T.A on this? We're unable to move forward on the Expo upgrade again due to Bugsnag not supporting it yet.

**Comment by luke-belton** [comment]
Hi @kennethlynne - apologies for the delay getting this out, our CI has flagged up a potential issue with missing render errors through error boundaries on iOS, however we've so far been unable to reproduce this in a way that explains the test failure as we don't see this in ad-hoc app testing.
 
Our engineering team are actively working on this and hope to have a further update later in the week – with any luck, a `v46` of `bugsnag-expo` with a full run of our tests. As always we'll keep this thread updated with progress.

**Comment by foolem** [comment]
+1

**Comment by luke-belton** [comment]
Hi - just a quick update to let you know that we released support for `v46` of Expo in [`v46.0.0`](https://github.com/bugsnag/bugsnag-expo/releases/tag/v46.0.0) of bugsnag-expo 🎉
