### ISSUE TITLE
Typo in plugin-expo-eas-sourcemaps

### ISSUE THREAD

**Issue by evelant** [bugsnag/bugsnag-expo#56]
https://github.com/bugsnag/bugsnag-expo/blob/c37c324c8ab0afe4d8f1af28aff4bbf7f9acba8b/packages/plugin-expo-eas-sourcemaps/src/android.js#L54-L56

I don't think `:[7.3.0,) ` is valid gradle groovy syntax for a classpath version specifier, is it?

**Comment by luke-belton** [comment]
Hi @evelant - we believe that this is valid syntax for setting a minimum version, and has passed all our tests. Are you seeing an error that's leading you to believe this is invalid?

**Comment by evelant** [comment]
There was an issue elsewhere in my build that caused some confusion, sorry for the distraction!
